var bohaterowie_male = [
"Iron Man",
"Punisher",
"DareDevil",
"Iron Fist",
"Kapitan Ameryka",
"Ghost Rider",
"Thor",
"Hulk",
"Spider Man",
"Luke Cage",
"Wolverine",
"Czarna Pantera",
"Doktor Strange",
"DeadPool",
"DeathLok",
"Warlock",
"Hawkeye",
"Ludzka Pochodnia",
"Nick Fury",
"Namor",
"Blade",
"Star Lord",
"Szop Rocket",
"Nova",
"Bucky",
"Vision",
"Ant-Man",
"Cyklops",
"Mr Fantastic"
];

var bohaterowie_female = [
"Kapitan Marvel",
"Mocking Bird",
"Scarlet Witch",
"Spider Gwen",
"Gwen Pool",
"Wasp",
"Gwen Stancy",
"Gamora",
"Spider Girl",
"Czarna Wdowa",
"Jessica Jones",
"She Hulk",
"Dagger",
"Mary Jane",
"Jean Grey",
"Biały Tygrys",
"Walkiria",
"Karen Page",
"Vanessa",
"HellCat",
"Hela",
"Kitty Pride",
"Elektra"
];

var evilman = [
"Kingpin",
"Thanos",
"Dr Doom",
"Profesor X",
"Venom",
"Ichabod",
"Purple Man",
"HobGoblin",
"Red Skull",
"Sabertooth",
"Foggy Nelson",
"Loki",
"Juggernut",
"Green Goblin",
"Norman Osborn",
"Killmonger",
"Ronan Oskarżyciel",
"Ultron",
"J. Jonah Jameson",
"Mefisto",
"Janusz Tracz"
];

var aktorzy_male = [
"Mikołaj Roznerski",
"Wojciech Cejrowski",
"Korwin",
"Bercik",
"Marcin Daniec",
"Abelard Giza",
"Robert Górski",
"Cezary Pazura",
"ten menel spod sklepu",
"proboszcz",
"papież",
"Artur Andrus",
"Eugeniusz Bono",
"Tadeusz Drozda",
"Krzysztof Czeczot",
"Paweł Domagała",
"Łukasz Garlicki",
"Jan Frycz",
"Tomasz Kot",
"Piotr Adamczyk",
"Wojciech Mecwaldowski",
"Tomasz Karolak",
"Maciej Stuhr",
"Borys Szyc",
"Zbigniew Zamachowski",
"Rafał Królikowski",
"Michał Koterski",
"Maciej Zakościelny",
"Paweł Małaszyński",
"Rafał Cieszyński",
"Mateusz Damięcki",
"Wojciech Solarz",
"Jakub Wesołowski",
"Rafał Rutkowski",
"Piotr Głowacki",
"Dariusz Kowalski",
"Paźdioch",
"Ferdek Kiepski",
"Waldemar Kiepski"
];

var aktorzy_female = [
"Weronika Rosati",
"Barbara Kurdej-Szatan",
"Anna Dereszowska",
"Danuta Stenka",
"Anna Mucha",
"Katarzyna Figura",
"Katarzyna Bujakiewicz",
"Sonia Bohosiewicz",
"Małgorzata Kożuchowska",
"Agnieszka Dygant",
"Magdalena Różczka",
"Anna Dereszowska",
"Marta Żmuda Trzebiatowska",
"Edyta Olszówka",
"Małgorzata Socha",
"Katarzyna Zielińska",
"Roma Gąsiorowska",
"Izabela Kuna",
"Olga Bołądź",
"Joanna Bartel",
"Agnieszka Więdłocha"
];

var zawod = [
"dołączył się do X-men ",
"dołączył do Defenders",
"usmażył złotą rybkę",
"znalazł buga w Windowsie",
"trenuje crossfit",
"ma problemy emocjonalne",
"ma problem ze swoją płcią",
"został lewakiem",
"zaczął robić karierę rapu z Eminemem",
"naucza w kościele Latającego Potwora Spaghetti",
"zostaje prezydentem Polski",
"pracuje dla Janusza Tracza",
"został żebrakiem",
"ma problemy psychiczne",
"pobił rysownika Marvela",
"skończył szkołę marketingu",
"został programistą baz danych",
"skoczył z mostu",
"pracuje w cyrku",
"zbudował autobota",
"rozmawia z kosmitami",
"został menelem",
"został coachem",
"zgwałcił Skrulla",
"zagiął Matta Murlocka w znajomości prawa",
"nasrał do zbroi",
"odkrył, skąd biorą się dzieci",
"nasikał sobie do kostiumu",
"rozdaje ulotki",
"zwątpił w swój cel życiowy",
"zastanawia się, czemu nigdy nie spotkał Batmana",
"dołączył do Teen Titans",
"zniszczył mienie publiczne",
"został polskim kabareciarzem",
"ściga przestępców podatkowych",
"naucza w szkole",
"gra w Plebanii",
"pokłócił się z fanem DC",
"zdaje sesję",
"szuka pracy",
"pracuje jako sprzątacz",
"stał się kasjerem biedronki",
"złamał kość ogonową",
"tworzy memy",
"opiekuje się kotami",
"prowadzi hodowlę bocianów",
"pracuje w pralni",
"wyemigrował z Europy",
"hoduje wielbłądy",
"rysuje komiksy o swoich przygodach, jednak dostaje wypowiedzenie z pracy od Marvela",
"porzucił swoją przeszłość, i postanowił zostać kapłanem",
"zaczął nagrywać swoje utwory Disco Polo",
"wie, że Ziemia jest płaska",
"programuje w Javie"
];

var kto = [
"połowa Nowego Jorku",
"pieniądz",
"goście odpowiedzialni za MCU",
"koleżanka",
"premier",
"połowa Śląska",
"jego kostium",
"rząd USA",
"cały TVN",
"były Prezydent USA",
"ludkość od IT",
"jej ex-przyjacióła",
"jej ręka",
"Stalin",
"Rasputin",
"chinski cesarz",
"Hitler",
"jego teść",
"jego noga",
"jej pies",
"ich Bank",
"ich kot",
"chłopak",
"babcia",
"dziadek",
"chomik",
"Iron Maiden",
"Metallica",
"Modern Talking",
"Elvis Presley",
"ich ulubiony zespół disco polo",
"brat",
"połowa redakcji Daily Bugle",
"cały Marvel",
"kuzyn",
"ich sąsiad",
"ex"
];

var co_z_kobieta = [
"sprzedaje w warzywniaku",
"oddała się za pół darmo",
"próbowała owniąć go wokół palca",
"przepaliła pierogi",
"zrobiła sernik z budyniu",
"wygrała pasjansa kartami od Tarota",
"przesoliła zupę",
"prowadzi vbloga o modzie",
"skrytkowała polski rząd",
"odkryła że św Mikołaj nie istnieje",
"udowodniła, że Dinozaury zostały stworzone przez USA",
"stwierdziła, że ludzkość została stworzona przez kosmitów",
"stwierdziła, że Darth Vader istniał naprawdę",
"jest antyszczepionkowcem",
"skończyła europeistykę",
"zapłaciła podatek w naturze",
"przebłagała chłopaka, żeby kupił jej działkę",
"hoduje podejrzane kwiatki",
"nie zdała egzaminu gimnazjalnego",
"padła na pierwszym pytaniu w Milionerach",
"zdradziła go z sąsiadem",
"z zupy pomidorowej zrobiła rosół",
"została zwolniona z baru szybkiej obsługi",
"nie zdała matury",
"rozbiła samochód podczas egzaminu na prawo jazdy",
"poznała sekretną tożsamość jej chłopaka na Tinderze",
"stwierdziła, że film Batman vs Superman jest dziełem sztuki",
"przepaliła wodę",
"występuje w reklamie środków żrących",
"rozlała wódkę",
"przytyła o 20 kg",
"występuje jako aktorka porno",
"prowadzi burdel",
"zalega z czynszem",
"wypiła za dużo wódki",
"nie chciała spełnić jego chorych zachcianek",
"zaczeła kupować komiksy z DC"
];

var co_sie_dzieje = [
"zdradza ją z jej najlepszą koleżanką",
"ginie w wyniku eksplozji atomowej",
"ginie potrącony przez samochód",
"ginie w niewyjaśnionych okolicznościach",
"zostaje porwany przez UFO",
"był kosmitą",
"stwierdza że kłamie",
"przemawia dziwnym głosem",
"ukradł im pieniądze",
"odnalazło 7 smoczych kul",
"strzela focha",
"wzieła kredyt na nowy Smartfon",
"przestaje się do niej odzywać",
"posiada zdolności paranormalne",
"posiada zdolności magiczne",
"widziała Smoka",
"posiada zdolność rozmawiania ze zwierzętami",
"posiada zdolność latania",
"posiada kamień nieskończoności w swojej dupie",
"przechodzi na stronę zła",
"wykupili prenumeratę Daily Bugle",
"olało jej zaloty",
"dostaje moc rozbierania wzrokiem",
"dostaje misję uratowania wszechświata",
"zostaje wystrzelony na marsa bez powrotu",
"zostaje wysłany na misję samobójczą",
"znajduje portal prowadzący do uniwersum DC",
"trafia na wojownika z innego wymiaru"
];

var co_postanawia = [
"rzucić pracę",
"poznać nowego faceta",
"odnaleźć Zajączka Wielkanocnego",
"wykładać chemię w sklepie",
"dać silnik V8 z Ferrari do malucha",
"udać się do psychiatry",
"nauczyć się czegoś nowego",
"skoczyć z wieżowca",
"wyjechać za granicę",
"zostać feministką",
"nauczyć się karate",
"zebrać kamienie nieskończoności",
"nakłonić Marvela by sprzedała jej postać do DC",
"zostać mnichem tybetańskim",
"wspiąć się na Mount Everest",
"nauczyć się gotować",
"nauczyć się tańczyć",
"dołączyć do SHIELD",
"dołączyć do HYDRY",
"dołączyć do HAMMER",
"skoczyć na bungee",
"zapolować na Złego Wilka (tego od trzech świnek)",
"wyruszyć na podróż by go / ją odszukać",
"się zemścić",
"znaleźć nową pracę",
"adoptować zwierzaka",
"zniszczyć wszechswiat",
"spędzać więcej czasu z rodziną",
"spędzić noc z jego sąsiadem",
"zrobić remont w domu",
"znaleźć innego faceta, póki jeszcze może",
"ugotować pierogi",
"zapytać Kulfona o poradę zawodową",
"wyprostować ucho Uszatkowi",
"zadzwonić do teściowej",
"pić wino do samego rana",
"rzucić ten związek i spędzić dalsze życie z kotami",
"odnaleźć Kun-lun i sprać dupsko Iron Fistowi",
"ukraść tron Thanosowi",
"rzucić to wszystko i wyjechać w Bieszczady"
];

var a_co_z_wrogiem = [
"przeciera oczy ze zdziwienia",
"przeprasza za II Wojnę Światową",
"prowadzi program na TVN24",
"stworzył o tym odcinek w programie paradokumentalnym", 
"zgłosił ich sprawę do programu ,,Sprawa dla reportera''",
"prowadzi partię polityczną z programem likwidacji patologii, jaką tworzą nasi bohaterowie",
"trzyma kciuki za ich związek",
"wypuł kawę gdy o tym usłyszał",
"otrzymał zaproszenie na ich ślub",
"prowadzi przeciwko im stronę internetową",
"włamał się na ich konto na facebooku",
"przekonał Netflixa do stworzenia o tym serialu",
"puknął się w głowę",
"strzelił sobie w łeb",
"stracił nadzieję na romans",
"szuka żony na Tinderze",
"próbuje sprzedać malucha za pół miliona złotych",
"wie jak z Polski zrobić potęgę ekonomiczną",
"wygrał wybory do Rady Europejskiej",
"chwali się jakim potężnym artefaktem jest paszport Polsatu",
"nakłonił ich kota, by nasrał im na łózko",
"nakłonił ich psa, by dolał trucizny do ich zupy",
"sprzedał im kradzioną złotówkę za 5 zł",
"powiadomił o tym służby",
"podał ich do sądu",
"był jej poprzednim kochankiem",
"napisał hejty na ich kanale youtube",
"został ich lokajem",
"nie wie, że jest ojcem jej przyszego dziecka",
"wstał i zaczął bić im brawo",
"podstawił im pod drzwi stado kotów, coś przy tym sugerując...",
"napisał książkę bestseller o ich życiu",
"zaczął kwestionować w swój sens życia",
"czasami odwiedza ją w nocy"
];

var ale_czy_co = [
"ich związek przetrwa próbę czasu",
"przekonają lewaków do prawicowych ideii?",
"uda im się wywołać Batmana, gdy użyli symbolu Supermana na latarnii",
"uda im się odnaleźć Power Rangers",
"uda im się wywołać Kapitana Planetę",
"zakończyć wojnę na Cybertronie",
"przekonać Linuxiarzy do Windowsa",
"przekonać PC Master Race do konsol",
"stworzą crossovera z DC",
"czy wróg uwiedzie ją zanim się pobiorą",
"uda im się wejść do Narnii za pomocą sedesu",
"uratują Disneyland przed Wojną Klonów",
"powstrzymają Thanosa przed jego zabawą z palcami",
"przekonają polskich raperów do zagrania z nimi utowru",
"wygrają turniej 1 z 10",
"udowodnią, że Ziemia jest naleśnikiem, a Mars sernikiem",
"Warszawa obroni się przed hordą zmutowanych zombie",
"wyborcy zagłosują na zmiennokształtnego jaszczura w ciele człowieka",
"meteory zniszczą ziemię",
"dzięki temu DC Universe zacznie mieć lepsze wyniki finansowe",
"dostaną pieniądze z 500+, gdy mają wyższe zarobki",
"Peter Parker przestanie być takim ciamajdą",
"Polacy dostaną się do Mistrzostw Świata",
"walcząc z demonami dowiedzą się prawdy o sobie",
"zarobią na małego fiata",
"sługi Thanosa zaczną w Polsce uczciwie pracować",
"uda się zarobić na tym większą kasę",
"pokonają zło, jakie ciąży nad ziemią",
"unikną poborcy podatkowego",
"Polska dogoni gospodarczo całą Europę",
"Polska przetrwa atomową apokalipsę"
];

function losuj(tablica){
	return tablica[Math.floor(Math.random()*tablica.length)];
}

function odmien(imie){
	if(imie == "Paweł"){
		return "Pawła";
	}else if(imie == "Antoni"){
		return "Antoniego";
	}else if(imie == "Ksawery"){
		return "Ksawerego";
	}else if(imie == "Kacper"){
		return "Kacpra";
	}else if(imie == "Ignacy"){
		return "Ignacego";
	}else if(imie == "Franciszek"){
		return "Franciszka";
	}else{
		return imie + "a";
	}
}

function generuj(){
	var zdanie = losuj(bohaterowie_male) + " (" + losuj(aktorzy_male) + ") " +  losuj(zawod) + " i próbuje stworzyć związek z " + losuj(bohaterowie_female) + " (" + losuj(aktorzy_female) + ")" + ", która " + losuj(co_z_kobieta) + ". Niestety, okazuje się, że " + losuj(kto) + " " + losuj(co_sie_dzieje) + ", więc ona postanawia " + losuj(co_postanawia) + ". Tymczasem " + losuj(evilman) + " (" + losuj(aktorzy_male) + ") " + losuj(a_co_z_wrogiem) +". Ale czy " + losuj(ale_czy_co) + "?";
	document.getElementById("gen").innerText = zdanie;
}
